const friends = [
  "Cao Family",
  "Fadwa Sumrein, DO",
  "Zhang Family",
  "Gonzalez Family",
  "Yang Family",
  "Ortiz CPA, LLC",
  "The Yang Family",
  "Szchuan Delight",
  "Chakravarty Family",
  "Venkatraghvan Family",
  "Gee Family",
  "Fan Pan",
  "Dasilva Family",
  "Shukhat Family",
  "Devarshi LLC",
  "Abrams Family",
  "Tiwari Family",
  "Flyntz Family ",
  "Frankie Primerano",
  "Periscope Investment ",
  "ABBE Lumber",
  "Cory Mathews Barbershop",
  "Morales Family",
  "NJ Table Tennis Club",
  "Iyer Family",
  "Qin Family",
  "Tran Family",
  "Chan Family",
  "Onyeukwu Family",
  "Theocharopoulos Family",
  "Peneno Family",
  "Velette Family",
  "The Bike Stand",
  "Beauty By Design",
  "Chen Family",
  "Music and Movement Entertainment LLC",
  "Shanghai Mabcare Therapeutics",
  "Gonzalez Family",
  "Save-Raut Family",
  "Akin Family",
  "Aravali Marbles",
  "Highland Falls, LLC",
  "Springfield Orthodontics",
  "Westfield Pediatric Dental Group",
  "Robert T. Robinson, DDS PA",
  "Gary White DDS",
  "Yalcin Family",
  "Cesar-Kai Academy LLC",
  "Rob Pollack",
  "Dry Cut Hair Salon",
  "Westfield Limo and Car Service",
  "Premiere Health System LLC",
  "Chatham Dental Boutique",
  "Sulinski Family",
  "Simply Gorgeous Salon and Spa",
  "Besson Orthodontics",
  "Alluem Yoga",
  "The Blowout Lab",
  "Deaza-Camacho Family",
  "So Delicious Ice Cream",
  "Ajmal Family",
  "Ghate Family"
].sort((a, b) => a.localeCompare(b))

export default friends
